[tool.poetry]
name = "px4ctl"
version = "1.0.0a6"
description = "Command-line mission planning, execution and monitoring for MAVSDK"
authors = ["Quinn Thibeault <quinn.thibeault96@gmail.com>"]
license = "MIT"
packages = [
    {include = "px4ctl", from = "src"}
]
include = ["px4ctl/py.typed"]

[tool.poetry.dependencies]
python = "^3.7.0"
attrs = "^21.0.0"
cattrs = "^1.7.1"
mavsdk = "^0.17.0"
click = "^8.0"
Sphinx = {version = "^3.5.4", optional = true}
sphinx-autodocgen = {version = "^1.2", optional = true}
sphinx-rtd-theme = {version = "^0.5.2", optional = true}
dronekit = "^2.9.2"

[tool.poetry.dev-dependencies]
mypy = "^0.812"
black = "^20.8b1"
pytest = "^6.2.3"
hypothesis = "^6.9.1"
pytest-asyncio = "^0.15.1"

[tool.poetry.scripts]
px4ctl = "px4ctl.__main__:px4ctl"

[tool.poetry.extras]
docs = ["sphinx", "sphinx-autodocgen", "sphinx-rtd-theme"]

[tool.black]
line-length = 99

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
