[tool.poetry]
name = "pymugen"
version = "1.2.0"
description = ""
authors = ["Alejandro Granados <agranadosb55199@outlook.com>"]

[tool.poetry.dependencies]
python = "^3.8"
PyVCF = "^0.6.8"
python-Levenshtein = "^0.12.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = {version = "^21.5b0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
