[tool.poetry]
name = "rocshelf"
version = "0"
description = "Препроцессор для компиляции веб-страниц из составляющих частей с параллельной модернизацией."
authors = ["rocshers <prog.rocshers@gmail.com>"]
readme = "readme.md"
homepage = "https://github.com/rocshers/rocshelf"
classifiers = [
    'Programming Language :: Python :: 3',
    'License :: OSI Approved :: MIT License',
    'Operating System :: OS Independent',
]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
rlogging = "0.1.8"
rcore = "0.1.11"
libsass = "0.20.1"
pyyaml = "5.4.1"
beautifulsoup4 = "4.9.3"
Pillow = "^8.2.0"
Django = {version = "^3.2.4", extras = ["django"]}

[tool.poetry.dev-dependencies]
pytest = "5.3.0"
mypy = "0.812"
mypy-extensions = "0.4.3"
twine = "3.4.1"
wheel = "0.36.2"
wemake-python-styleguide = "0.15.2"
flake8 = "^3.9.2"
autopep8 = "1.5.7"
snakeviz = "^2.1.0"

[tool.poetry-version-plugin]
source = "init"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
