[tool.poetry]
name = "thlink-backend-notification-lib"
version = "0.6.1"
description = "SNS Wrapper"
authors = ["thlink"]

[tool.poetry.dependencies]
python = "^3.7"
boto3 = "^1.17.78"
circuitbreaker = "^1.3.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
