[tool.poetry]
name = "rLogging"
version = "0.2.0"
description = "Модуль гибкого логирования python приложений"
authors = ["rocshers <prog.rocshers@gmail.com>"]
readme = "readme.md"
# homepage = "https://github.com/rocshers/rocshelf"
classifiers = [
    'Programming Language :: Python :: 3',
    'License :: OSI Approved :: MIT License',
    'Operating System :: OS Independent',
]
license = "MIT"
packages = [
    { include = "rlogging" },
    { include = "django_rlogging" },
]

[tool.poetry.dependencies]
python = "^3.9"
daemons = "1.3.2"
pyzmq = "22.0.3"
zmq = "0.0.0"
cleo = "^0.8.1"
celery = "^5.1.2"
redis = "^3.5.3"

[tool.poetry.dev-dependencies]
pytest = "6.2.2"
mypy = "0.812"
mypy-extensions = "0.4.3"
twine = "3.4.1"
wheel = "0.36.2"
wemake-python-styleguide = "0.15.2"
autopep8 = "1.5.7"

# [tool.poetry-version-plugin]
# source = "gittag"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
